# Сайты маркетплейсов и сайты, которые содержат только справочную информацию
NON_PRODUCT_DOMAINS = (
    "aliexpress.ru",
    "avito.ru",
    "pinterest.com",
    "pinterest.ru",
    "studfile.net",
    "lektsia.com",
    "studopediaru.com",
    "studopedia.ru",
    "wikipedia.org",
    "wildberries.ru",
    "translated.turbopages.org",
    "shedevrum.ai",
    "base.garant.ru",
    "internet-law.ru",
    "istock.info",
    "normadocs.ru",
    "ozon.ru",
    "rosgosts.ru",
    "psm-snab.ru",
    "allgosts.ru",
    "gostassistent.ru",
    "meganorm.ru",
    "fandom.com",
)
